baseurl = "http://martian-lang.org"
languageCode = "en-us"
title = "Martian"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Digitalcraftsman"
	description = "A material design theme for documentations."
	copyright = ""

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/digitalcraftsman/hugo-material-docs"

	version = "1.0"
	logo = "images/logo.png"
	favicon = ""

	permalink = "#"

	# Custom assets
	custom_css = ["martian.css"]
	custom_js  = []

	# Syntax highlighting theme
	#highlight_css  = ""

	[params.palette]
  	primary = "red"
  	accent  = "black"

  [params.font]
  	text = "Ubuntu"
  	code = "Ubuntu Mono"

[social]
	twitter = ""
	github  = "martian-lang"
	email   = "hello@email.com"


[[menu.main]]
	name   = "Home"
	url    = "/"
	weight = 1

[[menu.main]]
	name   = "What is Martian?"
	url    = "what-is-martian/"
	weight = 10

[[menu.main]]
	name   = "Getting Started"
	url    = "getting-started/"
	weight = 20

[[menu.main]]
	name   = "Writing Pipelines"
	url    = "writing-pipelines/"
	weight = 30

[[menu.main]]
	name   = "Running Pipelines"
	url    = "running-pipelines/"
	weight = 40

[[menu.main]]
	name   = "Inspecting Pipelines"
	url    = "inspecting-pipelines/"
	weight = 50

[[menu.main]]
	name   = "Writing Stages"
	url    = "writing-stages/"
	weight = 60

[[menu.main]]
	name   = "Advanced Features"
	url    = "advanced-features/"
	weight = 70

[[menu.main]]
	name   = "Language Details"
	url    = "language-details/"
	weight = 80

[[menu.main]]
	name   = "About"
	url    = "about/"
	weight = 90

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
